model_config:
  name: 'cllm'
  manual_seed: 42
  vocab_dim: 1024
  training_mode: cac_pre

  cac_learning_rate: 0.0001
  cac_weight_decay: 0.0001
  gt_learning_rate: 0.001
  gt_weight_decay: 0
  cm_learning_rate: 0.0001
  cm_weight_decay: 0.01
  cac_config:
    num_layers: 1
    attn_dim: 1024
    mlp_dim: 2048
    num_heads: 16
    dropout: 0.0
    attn_dropout: 0.0
  concept_config:
    concept1:
      token: 'Mathematics - Commutative Algebra'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept2: 
      token: 'Computer Vision and Pattern Recognition'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept3: 
      token: 'Artificial Intelligence'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept4: 
      token: 'Systems and Control'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept5: 
      token: 'Group Theory'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept6: 
      token: 'Computational Engineering, Finance, and Science'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept7: 
      token: 'Programming Languages'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept8: 
      token: 'Information Theory'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept9: 
      token: 'Data Structures and Algorithms'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept10: 
      token: 'Neural and Evolutionary Computing'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept11: 
      token: 'Statistics Theory'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
  # scheduler_gamma: 0.95

# '0': math.AC
# '1': cs.CV
# '2': cs.AI
# '3': cs.SY
# '4': math.GR
# '5': cs.CE
# '6': cs.PL
# '7': cs.IT
# '8': cs.DS
# '9': cs.NE
# '10': math.ST

data_config:
  dataset_name: "ccdv/arxiv-classification"
  tokenizer_name: "facebook/bart-base"
  max_length: 512
  batch_size: 16
  num_workers: 4
  train_val_test_split: [0.8, 0.1, 0.1]
  cac_pre: True
  save_cache: "Map_cache/arxiv"
  load_cache: "Map_cache/arxiv"

trainer_config:
  accelerator: 'gpu'
  devices: [2]  # 2 or [0, 1]
  max_epochs: 1000
  precision: 16-mixed

log_config:
  name: "cllm"
  save_dir: "logs/"
  check_dir: "logs/check"
  checkpoint: True
  model_summary: False
  
