model_config:
  name: 'cllm'
  manual_seed: 42
  vocab_dim: 1024

  cac_learning_rate: 0.001
  cac_weight_decay: 0.001
  gt_learning_rate: 0.001
  gt_weight_decay: 0.001
  cm_learning_rate: 0.0001
  cm_weight_decay: 0.001
  cac_config:
    num_layers: 1
    attn_dim: 1024
    mlp_dim: 2048
    num_heads: 16
    dropout: 0.0
    attn_dropout: 0.0
  concept_config:
    concept1:
      token: 'computer science'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept2: 
      token: 'mathematics'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept3: 
      token: 'physics'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept4: 
      token: 'quantitative biology'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept5: 
      token: 'quantitative finance'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept6: 
      token: 'statistics'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept7: 
      token: 'electrical engineering and systems science'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1
    concept8: 
      token: 'economics'
      attn_dim: 1024
      mlp_dim: 2048
      num_heads: 8
      num_layers: 6
      dropout: 0.1
      attn_dropout: 0.1

data_config:
  dataset_name: "openwebtext"
  tokenizer_name: "facebook/bart-base"
  max_length: 1024
  batch_size: 64
  num_workers: 4
  train_val_test_split: [0.8, 0.1, 0.1]
  streaming: True

trainer_config:
  accelerator: 'gpu'
  devices: [1]  # 2 or [0, 1]
  max_epochs: 10
  precision: 16-mixed
  max_steps: 10000
  val_check_interval: 1000

log_config:
  name: "cllm"
  save_dir: "logs/"
  check_dir: "logs/check"
  checkpoint: False
  model_summary: False
  
